//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOOPolomka
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewClientService
    {
        public int ClientServiceID { get; set; }
        public int ClientID { get; set; }
        public string Title { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<int> CountDoc { get; set; }
    }
}
