//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOOPolomka
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwClients
    {
        public int ID { get; set; }
        public string Gender { get; set; }
        public string FLP { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime Registration_date { get; set; }
        public Nullable<System.DateTime> Date_of_last_visit { get; set; }
        public Nullable<int> Visit_count { get; set; }
        public Nullable<decimal> All_Visit_Cost { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<decimal> All_Visit_Cost_End { get; set; }
        public string Color { get; set; }
    }
}
